### ISSUE TITLE
Most enpoints do not return valid json

### ISSUE THREAD

**Issue by widarlein** [Unarmed/internet-on-a-stick#2]
Valid json is preferred for easy parsing in calling applications. Keys are strings as well

`{ name: "markovName" }`

Should be

`{ "name": "markovName" }`

**Comment by Unarmed** [comment]
True. I am currently returning hand-crafted JSON. I'll remove it and let GSON do the serialzation instead. :)

**Comment by Unarmed** [comment]
Fixed in  c100f1646dfe2447c4664cbba08d789dcd88e46b
